// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "VipHot Liberal - Plataforma Premium de Conteúdo",
  description: "A plataforma mais moderna para criadores de conteúdo premium",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${poppins.variable} font-[family-name:var(--font-poppins)] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
